[package]
name = "rascii"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive", "unicode", "string"] }
image = "0.25.10"
imageproc = "0.26.2"
opencv = {version="0.98.2", features=["videoio"]}

[profile.release]
lto = true
codegen-units = 1